version: '3.8'

services:
  backend_rds: 
    image: 654654200977.dkr.ecr.eu-north-1.amazonaws.com/petp_rds_repo_test:latest
    environment:
      - CORS_ALLOWED_ORIGINS=http://petp-tf-bucket-test.s3-website.eu-north-1.amazonaws.com 
      - DB_NAME=marko_db         # Change to your actual DB name
      - DB_USER=postgres               # RDS username
      - DB_PASSWORD=adminadmin76!      # RDS password
      - DB_HOST=my-petp-db-test.ctsskiqw2d3n.eu-north-1.rds.amazonaws.com           # RDS instance identifier
      - DB_PORT=5432                   # Default Postgres port
      - REDIS_HOST=redis               # Hostname of the Redis service
      - REDIS_PORT=6379                # Default Redis port
      - REDIS_DB=0                     # Default Redis DB
    ports:
      - "8001:8001"  # Matches with the Load Balancer for RDS service
    depends_on:
      - db
      - redis

  backend_redis:
    image: 654654200977.dkr.ecr.eu-north-1.amazonaws.com/petp_redis_repo_test:latest
    environment:
      - CORS_ALLOWED_ORIGINS=http://petp-tf-bucket-test.s3-website.eu-north-1.amazonaws.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "8002:8002"  # Matches with the Load Balancer for Redis service
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=marko_db
      - POSTGRES_USER=postgres         # RDS username
      - POSTGRES_PASSWORD=adminadmin76! # RDS password
    ports:
      - "5432:5432"
